language: r
sudo: required
cache: packages
env:
  global:
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - HDF5_VERSION=1.8.13
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
before_install:
- chmod +x travis_setup.sh
- "./travis_setup.sh"
r:
- bioc-devel
- bioc-release
notifications:
    slack: trapnell-lab:Dq2NoPKxteM8gLwIt9usY7mL
