language: r
sudo: required
cache: packages
env:
  global:
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - HDF5_VERSION=1.8.13
before_install:
- chmod +x travis_setup.sh
- "./travis_setup.sh"
r:
- bioc-devel
- bioc-release
notifications:
  slack:
    rooms:
      secure: hpLF333dNXWR0yWrDIr5VBeodsS4iqy2l+GoON1FFv2Evo9uaP6Ddlge0IRlmGfaRGw9Etf1/3TczpwzXIaPoIJeEv2zskPAC2KYYufcEqAPIknoEzDEYoI4IDWd52QpawJmVX/K2mJCl0iwkbKCRhUt95QYgvm869sTceuEw2nK0aW++tzw+HDx2qVzdf4L2t34MP5DPveYtlY+55ADbT2odaJw+wFrDpBxbUYauon7C3ZzQW9nHrTidTVnyaHfj2ivCz8LK8k9sTCRzdGBkSD3yOZEtHnfluocICpronsNDskP8arevpu6RJ6ecD2glc5mUPUoqvHVUI7AaDYe/zhqtAZics1H+0x+SP7cwYibNmjVJoGYOklfQ43a9PbscZrHzmIL6CqWMlotFJT5H1StDSJ/oaDyRAZDtdH9OHEQpyHUhlvRPPjhb24JjDEOMU//olLk0y++UrodGb+q+oqod8PvyXSNrH6vDAaBVz/5X1i8Utwm/ozQ27Wb3ExgPTIwdXM9hMn/z6nBznA1DIXg1QoYBvURy6PIrZ1fPuk5TyqylDvskAgWqby4BeDVcluiFzx0t0RLZDPfui84gsxdu9duTsnGYBk5pQUoXUx7QI/Pi3X0OTeRZiu87EiDRffRIloNqAgdprMDoAHfRqu7Qi56JKvMy/wumSHpwzI=#monocle
