language: r
cache: packages
before_script:
- sudo apt-get install hdf5-tools
r:
- bioc-devel
- bioc-release
notifications:
  slack:
    secure: STrddR3mWYyiJRrHnXeRg5N4KnERPnuMEB2+T4aozy9ELEaLP/LiENMOptGrQ7mIZoVOnRXKIsCU/4QOYC6+5icnJqTgrJKmVkOL7dZKIPKJ17SxCU2+5K6W63XNp8vQes552X017bcg18Wga1Pzi0Abee91TqgZbZqP3x7M/74VT55Sy9BQLlnY+GbreyDbTrZ0boeHGpshkwDfykLPOY+lJz9sGBBSsywpUeo0Mma7eUM0KjrbMKvVQ377DE5DlBfLn1SShDBhJSA4MfQkaXhnmuQyRCoSwzy3IS2rt0dXo70vC/quiH7HuZhew7bPWlWgzQaeseAK1nWspEJJOlRGPBZZoWgs3/jKgxco9J7OYLR1PGPIH7kuRpJYjrVC2Jc11FXecfSYEjRjZNbQP9GgZk3IRw17vtdDeK54vQlgf95IAvohuJeGoJbozfwmfaoKChQmSBqzdKGjoi/bkwFWiebLY0qrnP8JiGV/A7/jZl4Oq+4loYTCSD0nI6OX/E1SUKsTau4iYJAIixGWVHFxADxEHQHSgV4n50szKCIpgeGE9xQSF+nFkWDlc+z5amOEmrjJ8w3/Yp8eOXiY8tvv9uAWFZfMRNpxOjVb/P4tQ3NzLh0FHYEcGHevqVhzXiS0huYgnskC3CTsw9CUzAShtqARdAg7p1ufGTI3Zsg=
