language: r
sudo: required
cache: packages
env:
  global:
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - HDF5_VERSION=1.8.13
before_install:
- chmod +x travis_setup.sh
- "./travis_setup.sh"
r:
- bioc-devel
- bioc-release
notifications:
  slack:
    secure: sOki9jz6vIgSTrmTbvDP8m6M6XD68SonXiaKLeG5iIoKvM1EqO8P1N/EWNwSSUEMSQLqmSDrUDFg668y4iHiRW4RhRWTS3EoJavLQZ7jo7GBLU6UXFvcK6w1LXOGohADJuBWmn5xbx6JIh2kDwhQMhr98OW5jjwUQMtGBs0wb8skXvlUFgB5aPSWBfeDj92hjYZYYQe4fBaKu6iOLc2xHdFANIIGGVwT18mh7sGzCSXK5CrKEs4FyTLsr9LA195URisZ3Tl000jvr+Lr9LeZybAncR5q7hx6nR97hHF/58BSAgbn4cPVTZ1WELT2RVLcDI3bl3+xLaRYBSLqcCkA/n4q8W+fbF+ZhmS8uuZ6tXBf44t9pRgZwx2rVw/zvSgniLdJ01h9sZORoG9vRa8mdd1iIEonSQQ92t0viRZKm6tiSD4wFFbeNXS8puyBjAvSX0s05REr/Z4UUEDyazG5wYo7kjEyXZijKOHWZNpKBQyDRq2LjALg3QSOx/MjPXMPfLipSQvRWvYrrKJnSiRSwAowmSCrzyjv9zeGimw7G5Nc8vCyq17d6SZ9f6CwmXUSQK1QIVmf+8d+3/kQVCmav0XuMiwXBw2NEA1wtsZS5hNLiSXop2zpX/pHEQvGf/ZN2YGIuzbiRm9m/zCzbnCa3DUVKaflsm5dM6BRiRvg3gY=
