language: r
sudo: required
cache: packages
env:
  global:
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - HDF5_VERSION=1.8.13
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
before_install:
- chmod +x travis_setup.sh
- "./travis_setup.sh"
r:
- bioc-devel
- bioc-release
notifications:
  slack:
    secure: MbpFm6T9UFbwo8pnN9CMjlPYmR0Glrd+iyq1Ruxytqu97+dJB5fLa7N3FPsSI9o0f4vTFTEMSpyoOB6ryBicVNBcCbFPyafxwCMpUrw6wMrcU18DcmjC/JOkUYr7IN8CfTGP21EjtCbE1zx54w3PuxOrB4rAZR5zzceuBBvsT+J6BjwtyY7BPERKgtZ6v1HMo+9ufF19iEHwWKkFnen9Zn/BbzmcP4LRwXTejd53ojWc+6CpGiwoyfq4T3JIf6JoxdMEY3QC+JtVaANCVA9G4/UgEw9x1bhu9Sv5msXPwRx5OBvgPDFSCKxyvJK4aEBDwHAD0xZxUgUofthoc7BPyMuWOccbo0ECQB6u/hrXYQErqAcGbY8Eb3rw3LzIeTbaC41LcNFbFfiuSN0u1HL4mh8kdRI/Az4x/B5wKfSQDOTtWjtCqgC5oIwikj4kdtMTUsSb8hfkOta/Mskjj3z8dUsgRXKHM5c367l+N22gK1oHsDtGqB6yB8VfNok7rpYxhu64QWXZK+HgcVmI1y2xuAIy96rKpep8XUjk+4ac3DRnq9g2kIUewX1p5eeZlRXDyKsmdW04Absm0+ylRVVq02HyGQNGgA4njQCifticyuKT5ehDH2If9YJYFM6S6FVnC68C8ZDVcBe1AikhPOhS7EuCJeDFk9BGvvtbNf++FQk=
